[package]
name = "day18"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
thiserror = "1.0"
env_logger = "0.11.5"
regex = "1"
lazy_static = "1.4"